version: "3.9"

services:

    mongo:
        image: mongo
        hostname: mongo.${HOST}
        restart: always
        volumes:
            - mongodata:/data/db
        ports:
            - ${MONGO_PORT:-27017}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
    mongodata:
