name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: cars-brands:latest
          outputs: type=docker,dest=/tmp/cars-brands.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cars-brands
          path: /tmp/cars-brands.tar
          retention-days: 1
  lint:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: cars-brands
          path: /tmp
      - name: Run Eslint
        run: |
          docker load --input /tmp/cars-brands.tar
          docker run cars-brands:latest yarn lint
  test-unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: cars-brands
          path: /tmp
      - name: Run test:unit
        run: |
          docker load --input /tmp/cars-brands.tar
          docker run cars-brands:latest yarn test
  test-e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: cars-brands
          path: /tmp
      - name: Up MongoDB
        run: docker-compose -f "docker-compose.yaml" up -d --build
      - name: Run test:e2e
        run: |
          docker load --input /tmp/cars-brands.tar
          docker run --network=example-cars-brands_default cars-brands:latest yarn test:e2e
  build:
    runs-on: ubuntu-latest
    needs:
      - test-unit
      - test-e2e
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: cars-brands
          path: /tmp
      - name: Run build app
        run: |
          docker load --input /tmp/cars-brands.tar
          docker run cars-brands:latest yarn build
